#!/bin/bash
param1=$1
param2=$2
script_name=$0
#echo "Скрипт $script_name в $PWD"

javac -sourcepath src -d bin -classpath lib/htmlcleaner-2.6.1.jar src/fcl/html/GoogleTopTenParser.java

case $param1 in
-f)
java -classpath bin:lib/htmlcleaner-2.6.1.jar fcl.html.GoogleTopTenParser $param2
;;
-all)
folder=`ls $param2`
for files in $folder
do
echo "$files"
java -classpath bin:lib/htmlcleaner-2.6.1.jar fcl.html.GoogleTopTenParser $param2/$files
echo
done
;;
*)
echo "type commands [-commands] [parameters]
-f: [path to file] - parse single file
-all: [path to directory] - parse all files in folder"
esac

exit 0 
#!bash exit
